name: AriosBuild
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Theos
        # Hata veren yer burasıydı, bu güncel olanıdır:
        uses: ms7m/setup-theos-action@main
      - name: Build Tweak
        run: |
          make package FINALPACKAGE=1
      - name: Upload Dylib
        uses: actions/upload-artifact@v4
        with:
          name: AriosHome-Dylib
          path: .theos/obj/install/*.dylib
